SERVER_SOURCE := server_3
CLIENT_SOURCE := client

build:
	gcc $(SERVER_SOURCE)/$(SERVER_SOURCE).c -o $(SERVER_SOURCE)/$(SERVER_SOURCE)
	gcc $(CLIENT_SOURCE)/$(CLIENT_SOURCE).c -o $(CLIENT_SOURCE)/$(CLIENT_SOURCE)

build-server:
	gcc $(SERVER_SOURCE)/$(SERVER_SOURCE).c -o $(SERVER_SOURCE)/$(SERVER_SOURCE)

build-client:
	gcc $(CLIENT_SOURCE)/$(CLIENT_SOURCE).c -o $(CLIENT_SOURCE)/$(CLIENT_SOURCE)

run-server:
	./$(SERVER_SOURCE)/$(SERVER_SOURCE)

run-client:
	./$(CLIENT_SOURCE)/(CLIENT_SOURCE)
